#!/usr/bin/env bash

set -e

# CONFIG="install.conf.yaml"
CONFIG="config.yaml"
PLUGIN_DIR="plugins"
DOTBOT_DIR="${PLUGIN_DIR}/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${PLUGIN_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    --base-directory "${BASEDIR}" \
    --plugin "${PLUGIN_DIR}/dotbot-brew/brew.py" \
    --plugin "${PLUGIN_DIR}/dotbot-stow/stow.py" \
    --plugin "${PLUGIN_DIR}/dotbot-git/git.py" \
    --config "${CONFIG}" "${@}"
